## 4.1 NumPy N-dimensional Array

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

In [2]:
# create array
from numpy import array

In [3]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

In [4]:
# display array
print(a)

[1. 2. 3.]


In [5]:
a

array([1., 2., 3.])

In [6]:
# display array shape
print(a.shape)

(3,)


In [7]:
# display array data type
print(a.dtype)

float64


## 4.2 Functions to Create Arrays

In [9]:
# create empty array
from numpy import empty
a = empty([3,3], dtype=int)
print(a)

[[        1         1         0]
 [      660       960         0]
 [ 16777984     32766 749424176]]


In [10]:
# create zeros array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# create ones array
from numpy import ones
a = ones([1,5])
print(a)

[[1. 1. 1. 1. 1.]]


In [12]:
import numpy as np

In [14]:
np.ones((3,6,9))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

## 4.3 Combining Arrays

In [15]:
# create array with vstack
from numpy import vstack

a = [1,2,3]
b = [4,5,6]

c = vstack([a, b])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [16]:
# create array with hstack
from numpy import hstack

a = [1,2,3]
b = [4,5,6]

c = hstack([a, b])
print(c)
print(c.shape)

[1 2 3 4 5 6]
(6,)


In [20]:
from numpy import ones_like

myarray = [[1,5,9],
           [2,3,9],
           [8,6,7],
           [8,9,7]]

# Return an array of ones with the same shape and type as a given array.
d = ones_like(myarray)
print(d)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
from numpy import zeros_like

# Return an array of zeros with the same shape and type as a given array.
e = zeros_like(myarray)
print(e)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
from numpy import full

#Return a new array of given shape and type, filled with `fill_value`.
g = full((5, 5), 10)
print(g)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
