## 5.1 One-Dimensional List to Array

In [1]:
# create one-dimnentional array
from numpy import array

# list of data
data = [11,22,33,44,55]

# array or data
data = array(data)

print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


## 5.2 Two-Dimensional List of Lists to Array

In [2]:
# create two-dimensional array

# list of data
data = [[11,22],
        [33,44],
        [55,66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## 5.3 One-Dimensional Indexing

In [4]:
# index a one-dimensional array

# define array
data = array([11,22,33,44,55])

# index data
print(data[0])
print(data[4])


# negative array indexing
print(data[-1])
print(data[-5])

11
55
55


IndexError: index -6 is out of bounds for axis 0 with size 5

## 5.4 Two-Dimensional Indexing

In [9]:
# index two-dimensional array
from numpy import array
# define array
data = array([[11,22],
              [33,44],
              [55,66]])
# index data
print(data[0,0])

# If we are interested in all items in the first row, we could leave the second dimension index
# empty
print(data[0])

11
[11 22]


## 5.5 One-Dimensional Slicing

In [5]:
# The slice extends from the from index and ends one item before the to index.
# define array
data = array([11,22,33,44,55])
print(data[:]) # => print all elements

[11 22 33 44 55]


In [6]:
# slice a subset of a one-dimensional array
print(data[0:1])

[11]


In [7]:
# negative slicing of a one-dimensional array
print(data[-2:])

[44 55]


In [8]:
# split input and output data
# define array
data = array([[11,22,33],
              [44,55,66],
              [77,88,99]])

In [10]:
# seperate data
X, y = data[:, :-1], data[:, -1]

X, y

(array([[11, 22],
        [44, 55],
        [77, 88]]),
 array([33, 66, 99]))

In [20]:
# split train and test data
data = array([[11,22,33],
              [44,55,66],
              [77,88,99]])

# seperate data
split = 2

train, test = data[:split,:], data[split:,:]

train, test

(array([[11, 22, 33],
        [44, 55, 66]]),
 array([[77, 88, 99]]))

## 5.6 Data Shape

In [11]:
# define array
data = array([11,22,33,44,55])
print(data.shape)

(5,)


In [12]:
# shape of two-dimensional array
data = array([[11,22],
            [33,44],
            [55,66]])
print(data.shape)

(3, 2)


In [13]:
# row and column shape of two-dimensional array

# list of data
data = [[11,22],
        [33,44],
        [55,66]]

# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Columns: %d' % data.shape[1])

Rows: 3
Columns: 2


## 5.7 Reshape 1D to 2D Array

In [15]:
# define array
data = array([11,22,33,44,55,66])
print(data.shape)

(6,)


In [16]:
# reshape
data = data.reshape(2,3)
print(data.shape)
print(data)

(2, 3)
[[11 22 33]
 [44 55 66]]


## 5.8 Reshape 2D to 3D Array

In [17]:
# list of data
data = [[11,22],
        [33,44],
        [55,66]]

# array of data
data = array(data)
print(data.shape)

(3, 2)


In [37]:
# reshape
data = data.reshape(2,3)

print(data.shape)
print(data)

(2, 3)
[[11 22 33]
 [44 55 66]]


## 5.9. Size

In [40]:
data = [[11,22],
        [33,44],
        [55,66]]

# array of data
data = array(data)

data.size

6