## 6.1 Scalar and One-Dimensional Array

In [1]:
# broadcast scalar to 1D array
from numpy import array

# define array
a = array([1,2,3])

print(a)

[1 2 3]


In [3]:
# define scalar
b = 2

# broadcast 
c = a + b
print(c)

[3 4 5]


In [4]:
# broadcast scalar to 2D array
# define array
A = array([[1,2,3],
           [1,2,3]])
print(A)

[[1 2 3]
 [1 2 3]]


In [5]:
# define scalar
b = 2

# broadcast
c = A + b
print(c)

[[3 4 5]
 [3 4 5]]


In [6]:
# define 2D array
A = array([[1,2,3],
           [1,2,3]])

# define 1D array
b = array([1,2,3])

# broadcast
C =  A + b
print(C)

[[2 4 6]
 [2 4 6]]


## 6.2 Limitations of Broadcasting

In [9]:
# broadcasting error

# define 2D array
A = array([[1,2,3],
           [1,2,3]])

print(A.shape)

(2, 3)


In [10]:
# define 1D array
b = array([1,2])
print(b.shape)

(2,)


In [11]:
# attempt to broadcast
C = A + b
print(C)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 