## 7.1 Defining a Vector

In [1]:
# create a vector
from numpy import array

# define a vector
v = array([1,2,3])
v

array([1, 2, 3])

## 7.2 Vector Addition

In [2]:
# define first vector
a = array([1,2,3])
print(a)

[1 2 3]


In [3]:
# define second vector
b = array([1,2,3])
print(b)

[1 2 3]


In [4]:
# add vectors
c = a + b
print(c)

[2 4 6]


## 7.3 Vector Subtraction

In [5]:
# define first vector
a = array([1,2,3])
print(a)

[1 2 3]


In [6]:
# define second vector
b = array ([0.5,0.5,0.5])
print(b)

[0.5 0.5 0.5]


In [7]:
# substraction
c = a - b
d = b - a

In [8]:
print(c)
print(d)

[0.5 1.5 2.5]
[-0.5 -1.5 -2.5]


## 7.4 Vector Multiplication

In [9]:
# define first vector
a = array([1,2,3])
print(a)

[1 2 3]


In [10]:
# define second vector
b = array([1,2,3])
print(b)

[1 2 3]


In [11]:
# multiply vectors
c = a * b
d = a ** b

In [12]:
print(c)
print(d)

[1 4 9]
[ 1  4 27]


## 7.5 Vector Division

In [13]:
# define first vector
a = array([1,2,3])
# define second vector
b = array([1,2,3])

In [14]:
c = a/b
print(c)

[1. 1. 1.]


In [15]:
d = array([4,16,25])
e = array([2,2,2]) # returns int

In [16]:
f = d//e
print(f)

[ 2  8 12]


## 7.6 Vector Dot Product

In [17]:
# define first vector
a = array([1,2,3])

# define second vector
b = array([1,2,3])

In [19]:
# multiply vectors
c = a.dot(b)
print(c)

14


## 7.7 Vector-Scalar Multiplication

In [20]:
# define vector
a = array([1,2,3])

# define scalar
s = 0.5

In [21]:
a * s

array([0.5, 1. , 1.5])