## 9.1 Defining a Matrix

In [1]:
# create matrix
from numpy import array
A = array([[1,2,3],
           [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


## 9.2 Matrix Addition

In [2]:
# define first matrix
A = array([[1,2,3],
           [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
# define second matrix
B = array([[1,2,3],
           [4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [4]:
# add matrices
C = A + B
print(C)

[[ 2  4  6]
 [ 8 10 12]]


## 9.3 Matrix Subtraction

In [5]:
C = A - B
print(C)

[[0 0 0]
 [0 0 0]]


## 9.4 Matrix Multiplication (Hadamard Product)

In [7]:
# matrix hadamard product
# C = A ◦ B

# multiply matrices
C = A * B
print(C)

[[ 1  4  9]
 [16 25 36]]


## 9.5 Matrix-Matrix Multiplication

In [8]:
# Matrix multiplication, also called the matrix dot product is more complicated than the previous
# operations and involves a rule as not all matrices can be multiplied together.
# C = A · B

Matrix A has the dimensions m rows and n columns and matrix B has the
dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix
with m rows and k columns.
C(m, k) = A(m, n) · B(n, k)

In [9]:
# define first matrix
A = array([[1,2],
           [3,4],
           [5,6]])

# define second matrix
B = array([[1,2],
           [3,4]])

# multiply matrices
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [10]:
# multiply matrices using @ operater (Python 3.5)
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]


## 9.6 Matrix-Vector Multiplication
A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that **the number of columns** in the **matrix** must **equal** **the number of
items** in the **vector**. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.

In [12]:
# c = A · v
# define matrix
A = array([[1, 2],
           [3, 4],
           [5, 6]])

# define vector
B = array([0.5, 0.5])

# multiply
C = A.dot(B)
print(C)

[1.5 3.5 5.5]


In [13]:
C = A.dot(B)

In [14]:
# multiply matrices using @ operater (Python 3.5)
D = A @ B
print(D)

[1.5 3.5 5.5]


## 9.7 Matrix-Scalar Multiplication

In [15]:
# C = A · b

# define matrix
A = array([[1, 2],
           [3, 4],
           [5, 6]])

# define scalar 
b = 0.5

# multiply
C = A * b
print(C)

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## 9.5 Matrix Division

In [17]:
# One matrix can be divided by another matrix with the same dimensions.
# define first matrix
A = array([[1,2,3],
           [4,5,6]])

# define second matrix
B = array([[1,2,3],
           [4,5,6]])

# divide matrices
C = A // B
print(C)

[[1 1 1]
 [1 1 1]]


In [18]:
A = array([[1,2,3],
           [4,5,6],
           [3,6,8]])

# define second matrix
B = array([[1,2,3],
           [4,5,6],
           [5,6,7]])
A.dot(B)

array([[ 24,  30,  36],
       [ 54,  69,  84],
       [ 67,  84, 101]])

In [20]:
import numpy as np