In [36]:
# 10.2 Square Matrix
# A square matrix is a matrix where the number of rows (n) is equivalent to the number of
# columns (m).
# n ≡ m
'''The square matrix is contrasted with the rectangular matrix where the number of rows and
columns are not equal. Given that the number of rows and columns match, the dimensions are
usually denoted as n, e.g. n × n. The size of the matrix is called the order, so an order 4 square
matrix is 4 × 4. The vector of values along the diagonal of the matrix from the top left to the
bottom right is called the main diagonal. Below is an example of an order 3 square matrix.'''
from numpy import array

SM = array([[1,2,3],
           [1,2,3],
           [1,2,3]])
print('Square Matrix\n',SM,'\n')

# 10.3 Symmetric Matrix
# A symmetric matrix is a type of square matrix where the top-right triangle is the same as the
# bottom-left triangle.
SyM = array([[1,2,3,4,5],
            [2,1,2,3,4],
            [3,2,1,2,3],
            [4,3,2,1,2],
            [5,4,3,2,1]])
print('Symmentric Matrix\n',SyM, '\n')

# 10.4 Triangular Matrix
'''A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left
of the matrix with the remaining elements filled with zero values. A triangular matrix with
values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular
matrix with values only below the main diagonal is called a lower triangular matrix.'''

# triangular matrix
from numpy import array
from numpy import tril
from numpy import triu

# define square matrix
M = array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(M)

# lower triangular matrix
lower = tril(M)
print('lower \n',lower)

# upper triangular matrix
upper = triu(M)
print('upper \n',upper)

Square Matrix
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

Symmentric Matrix
 [[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
lower 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
upper 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [37]:
# 10.5 Diagonal Matrix
'''A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal.'''

# diagonal matrix
from numpy import array
from numpy import diag

# define square matrix
M = array([[1,2,3],
          [1,2,3],
          [1,2,3]])
print(M)

#extract diagonal vector
d = diag(M)
print(d)

# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [1]:
import numpy as np

In [38]:
# 10.6 Identity Matrix
'''An identity matrix is a square matrix that does not change a vector when multiplied. The
values of an identity matrix are known. All of the scalar values along the main diagonal (top-left
to bottom-right) have the value one, while all other values are zero.'''
'''An identity matrix is a matrix that does not change any vector when we multiply
that vector by that matrix.'''

'''Alone, the identity matrix is not that interesting, although it is a component in other import
matrix operations, such as matrix inversion'''
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# 10.7 Orthogonal Matrix
'''Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1
then the vectors are called orthonormal because they are both orthogonal and normalized.'''
# v · w = 0
'''An orthogonal matrix is a square matrix whose rows are mutually orthonormal and
whose columns are mutually orthonormal'''

''' Orthogonal matrices are useful tools as they are
computationally cheap and stable to calculate their inverse as simply their transpose.'''
# orthogonal matrix
from numpy import array
from numpy.linalg import inv

# define orthogonal matrix
Q = array([[1,0],
          [0,-1]])
print(Q)

# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)

# identify equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


In [53]:
'''10.8 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Modify each example using your own small contrived array data.
ˆ Write your own functions for creating each matrix type.
ˆ Research one example where each type of array was used in machine learning'''

# square matrix
SM = array([[1,2,3],
           [1,2,3],
           [1,2,3]])
print(SM)

# Symmantic matrix
SyM = array([[1,2,3,4,5,6],
            [2,1,2,3,4,5],
            [3,2,1,2,3,4],
            [4,3,2,1,2,3],
            [5,4,3,2,1,2],
            [6,5,4,3,2,1]])
print(SyM, '\n')

# triangular matrix
M = array([[1,2,3],
          [1,2,3],
          [1,2,3]])

# upper
upper = triu(M)
print(upper, '\n')

# lower
lower = tril(M)
print(lower)

# diagonal matrix
#extract diagonal vector
d = diag(M)
print('\n',d,'\n')

# create diagonal matrix from vector
D = diag(d)
print(D,'\n')

# identity matrix
I = identity(10)
print(I,'\n')

# orthogonal matrix
Q = array([[-10, 2],
          [3, -7]])
print(Q)

# inverse equivalence
V = inv(Q)
print(V)
print(Q.T)

# identify equivalence
J = Q.dot(Q.T)
print(J)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 4 5 6]
 [2 1 2 3 4 5]
 [3 2 1 2 3 4]
 [4 3 2 1 2 3]
 [5 4 3 2 1 2]
 [6 5 4 3 2 1]] 

[[1 2 3]
 [0 2 3]
 [0 0 3]] 

[[1 0 0]
 [1 2 0]
 [1 2 3]]

 [1 2 3] 

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] 

[[-10   2]
 [  3  -7]]
[[-0.109375 -0.03125 ]
 [-0.046875 -0.15625 ]]
[[-10   3]
 [  2  -7]]
[[104 -44]
 [-44  58]]


In [ ]:
# ˆ Research one example where each type of array was used in machine learning.
# https://www.mathworks.com/help/stats/examples/statistics-and-machine-learning-with-big-data-using-tall-arrays.html
# https://towardsdatascience.com/20-popular-machine-learning-metrics-part-1-classification-regression-evaluation-metrics-1ca3e282a2ce