In [2]:
# 11.2 Transpose
from numpy import array
'''A defined matrix can be transposed, which creates a new matrix with the number of columns
and rows flipped.'''

# define matrix
A = array([[1,2],
           [3,4],
           [5,6]])
print(A)

# calculate transpose
print(A.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [5]:
# 11.3 Inverse
'''Matrix inversion is a process that finds another matrix that when multiplied with the matrix,
results in an identity matrix.'''
'''A matrix is invertible if there exists another matrix that results in the identity matrix, where
not all matrices are invertible. A square matrix that is not invertible is referred to as singular.'''

# invert matrix
from numpy import array
from numpy.linalg import inv

# define matrix
A = array([[1.0,2.0],
          [3.0,4.0]])
print(A)

# invert matrix
B = inv(A)
print(B)

# multiply A and B
I = A.dot(B)
print(I)

'''Matrix inversion is used as an operation in solving systems of
equations framed as matrix equations where we are interested in finding vectors of unknowns.
A good example is in finding the vector of coefficient values in linear regression.'''

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [9]:
# 11.4 Trace
'''A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left
to bottom-right).'''

# matrix trace
from numpy import array
from numpy import trace

# define matrix
A = array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(A)

# calculate trace
B = trace(A)
print(B, '1+5+9')

'''Alone, the trace operation is not interesting, but it offers a simpler notation and it is used
as an element in other key matrix operations.'''

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15 1+5+9


In [39]:
# 11.5 Determinant
'''The determinant of a square matrix is a scalar representation of the volume of the matrix'''

# metrix determinant
from numpy import array
from numpy.linalg import det

# define matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(A)

# calculate the determinant
B = det(A)
print(B)
print(1*(5*9-6*8)-2*(4*9-6*7)+3*(4*8-5*7))
#symbolab.com/solver/matrix-determinant-calculator/%5Cdet%20%5Cbegin%7Bpmatrix%7D1%20%26%202%20%26%203%20%5C%5C4%20%26%205%20%26%206%20%5C%5C7%20%26%208%20%26%209%5Cend%7Bpmatrix%7D?or=ex

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16
0


In [44]:
# 11.6 Rank
'''The rank of a matrix is the estimate of the number of linearly independent rows or columns in
a matrix. The rank of a matrix M is often denoted as the function rank().'''
# vector rank
from numpy import array
from numpy.linalg import matrix_rank

# rank
v1 = array([1,2,3])
print(v1)

vr1 = matrix_rank(v1)
print(vr1)

# zero rank
v2 = array([0,0,0,0,0])
print(v2)

vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [48]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank

# rank 0
M0 = array([[0,0],
           [0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)

# rank 1
M1 = array([[1,2],
           [1,2]])
mr1 = matrix_rank(M1)
print(mr1)

# rank 2
M2 = array([[1,2],
           [3,4]])
mr2 = matrix_rank(M2)
print(mr2)
# https://i.stack.imgur.com/ZsnTY.png

[[0 0]
 [0 0]]
0
1
2


In [95]:
'''11.7 Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
ˆ Modify each example using your own small contrived array data.
ˆ Write your own functions to implement one operation.
ˆ Research one example where each operation was used in machine learning.'''

from numpy import array
from numpy.linalg import inv
from numpy import trace
from numpy.linalg import det
from numpy.linalg import matrix_rank

# transpose
A = array([[2,4,6],
          [8,10,12],
          [14,16,18],
          [20,22,24]])
print(A)
print(A.T, '\n')

# inverse
A = array([[2.1,3.1],
          [4.1,5.1]])
print(A)

B = inv(A)
print(B)

I = A.dot(B)
print(I,'\n')

# trace
A = array([[2,4,16],
          [32,64,128],
          [256,512,1024]])
B = trace(A)
print(B)
print(2+64+1024)

# determinant
A = array([[1,450,3],
         [1,1,1],
         [50,12,1]])
B = det(A)
print(B,'\n')

# vector rank
v1 =  array([33,66,99])
print(v1)

vr1 = matrix_rank(v1)
print(vr1)

v2 = array([0,0,0,0])
print(v2)

vr2 = matrix_rank(v2)
print(vr2)

# metrix rank
# rank 0
M0 = array([[0,0],
           [0,0]])
print(M0)

# rank 1
mr0 = matrix_rank(M0)
print(mr0)

M1 = array([[33,66],
           [33,66]])
mr1 = matrix_rank(M1)
print(mr1)

# rank 2
M2 = array([[4,5],
          [6,7]])
mr2 = matrix_rank(M2)
print(mr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[ 2  8 14 20]
 [ 4 10 16 22]
 [ 6 12 18 24]] 

[[2.1 3.1]
 [4.1 5.1]]
[[-2.55  1.55]
 [ 2.05 -1.05]]
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]] 

1090
1090
21924.999999999985 

[33 66 99]
1
[0 0 0 0]
0
[[0 0]
 [0 0]]
0
1
2


In [ ]:
# ˆ Research one example where each operation was used in machine learning.'''
# https://www.quora.com/Why-do-we-transpose-matrices-in-machine-learning
'''You’ll see a lot of matrix transpositions in neural networks and deep learning. 
These ML models are nothing but a series of linear transformation of matrices 
(leave aside non-linear activation at the moment). Thus, you’ll need to match 
the matrix dimensions for computation, and that’s really the only reason you transpose matrices.'''